'TOME': addBook.php File Reference
addBook.php File Reference
Classes
class update_hook
Variables
$path = "./"
$pageTitle = "Add Book"
$result = DatabaseManager::checkError("select `name` from `libraries` where `ID` = '".$_SESSION["libraryID"]."'")
$libraryName = DatabaseManager::fetchAssoc($result)
$redir = redir_pop()
$form = new Form(Form::ADD, $redir)
$fieldset = new Fieldset_Vertical($form->getFormType())
$isbn = $_SESSION["post"]["isbn"]
$linkField = $fieldset->addField(new ISBNField("isbn13", "ISBN13", 13, true, true), $isbn13)
$row = new RowManager("bookTypes", $keyField->getName())
$hooks [] = new update_hook($keyField, $redir)
print $_SESSION ["post"]["email"]
print $_SESSION ["post"]["expires"]
print $_SESSION ["post"]["comments"]
print $libraryName ["name"]
Variable Documentation
print $_SESSION["post"]["comments"]
print $_SESSION["post"]["expires"]
print $_SESSION["post"]["email"]
Referenced by cleanSessionOnEmptyRedir(), getAvailableBooksForISBN(), getBookAvailability(), getProcessBookAssociation(), getProcessISBNCheckoutFieldset(), SecurityManager::isPageVisible(), SecurityManager::isRowVisible(), LoginManager::login(), SessionText::process(), SemesterUpdateHook::process(), CheckoutFormHook::process(), checkout_update_hoook::process(), update_hook::process(), redir_pop(), redir_push(), SessionText::show(), and SecurityManager::validatePage().
$fieldset = new Fieldset_Vertical($form->getFormType())
Referenced by Form::addFieldsets(), Form::display(), Fieldset_Horizontal::generate(), getProcessBookAssociation(), getProcessISBNCheckoutFieldset(), and Form::process().
$form = new Form(Form::ADD, $redir)
Referenced by SingleFilter::getForm(), getProcessBookAssociation(), and getProcessISBNCheckoutFieldset().
$hooks[] = new update_hook($keyField, $redir)
Referenced by Form::process().
print $isbn = $_SESSION["post"]["isbn"]
Referenced by showBookInfo(), and validateISBN().
print $libraryName["name"]
$libraryName = DatabaseManager::fetchAssoc($result)
$linkField = $fieldset->addField(new ISBNField("isbn13", "ISBN13", 13, true, true), $isbn13)
Referenced by getProcessBookAssociation(), and getProcessISBNCheckoutFieldset().
$pageTitle = "Add Book"
print $path = "./"
Referenced by Form::__construct(), addPage(), addPageLink(), Image::process(), CheckoutFormHook::process(), and SecurityManager::validatePage().
$redir = redir_pop()
Referenced by SecurityManager::validatePage().
$result = DatabaseManager::checkError("select `name` from `libraries` where `ID` = '".$_SESSION["libraryID"]."'")
Referenced by DatabaseManager::checkError(), DatabaseManager::fetchArray(), DatabaseManager::fetchAssoc(), DatabaseManager::fetchAssocArray(), generateAccessTable(), ListManager::generateList(), getBookAvailability(), SingleFilter::getForm(), RowManager::getRowManagers(), RowManager::initialize(), LoginManager::login(), DatabaseManager::multiCheckError(), ProcessBookAssociationHook::process(), CheckoutFormHook::process(), SecurityManager::setPermissions(), and LoginManager::suspend().
$row = new RowManager("bookTypes", $keyField->getName())
Referenced by DatabaseManager::fetchAssocArray(), getBookAvailability(), Fieldset::getDBValues(), SingleFilter::getForm(), getProcessISBNCheckoutFieldset(), LoginManager::login(), ProcessBookAssociationHook::process(), checkout_update_hoook::process(), update_hook::process(), SecurityManager::setPermissions(), and LoginManager::suspend().