'TOME': addClass.php File Reference
addClass.php File Reference
Variables
$path = "./"
$pageTitle = "Add Class"
$form = new Form(Form::ADD, $_SERVER["SCRIPT_NAME"])
$fieldset = new Fieldset_Vertical($form->getFormType())
$keyField = $fieldset->addField(new Hidden("ID", "", null, false))
$linkField = $fieldset->addField(new ClassIDField("class", "ID", array("maxlength"=>8), true, true))
$row = new RowManager("classes", $keyField->getName())
if(!empty($_REQUEST["text"])) print
Variable Documentation
$fieldset = new Fieldset_Vertical($form->getFormType())
$form = new Form(Form::ADD, $_SERVER["SCRIPT_NAME"])
$keyField = $fieldset->addField(new Hidden("ID", "", null, false))
Referenced by Fieldset_Horizontal::generate(), getProcessBookAssociation(), and getProcessISBNCheckoutFieldset().
$linkField = $fieldset->addField(new ClassIDField("class", "ID", array("maxlength"=>8), true, true))
$pageTitle = "Add Class"
$path = "./"
$row = new RowManager("classes", $keyField->getName())
if (!empty($_REQUEST["text"])) print
Referenced by addPage(), addPageLink(), DatabaseManager::checkError(), Fieldset::commit(), RowManager::delete(), Form::display(), Fieldset_Vertical::display(), Fieldset_Horizontal::display(), Form::displaySubmitButton(), CheckoutForm::displaySubmitButton(), RowManager::getModeText(), Form::getModeText(), ErrorLogManager::log(), DatabaseManager::multiCheckError(), ProcessBookAssociationHook::process(), showBookInfo(), showCheckoutForm(), and RowManager::update().