'TOME': Text Class Reference
Text Class Reference
Public Member Functions
display ()
process ()
Detailed Description
Handles display and processing of a Text field.
OPTIONAL $options["size"] - size of the form's text input field $options["maxlength"] - maximum length of text input field
Author:
John Oren
Version:
1.1 August 4, 2008
Member Function Documentation
Text::display ()
Prepares this form field for display.
Returns:
STRING HTML to display for the form field
Reimplemented from Field.
Reimplemented in Label.
References Field::$options, Field::getErrorText(), Field::getFieldName(), Field::getOptions(), Field::getValue(), and Field::isDelete().
Text::process ()
Processes this field and update the backend used by this field.
Returns:
BOOLEAN False if errors were encountered
Reimplemented from Field.
Reimplemented in ClassIDField, ISBNField, and LETUEmailField.
References Field::$options, Field::$value, Field::getFieldName(), Field::getOptions(), Field::isEmpty(), Field::isRequired(), Field::postProcess(), and Field::setEmpty().
The documentation for this class was generated from the following file:
OpenSiteAdmin/scripts/classes/Fields/Text.php