'TOME': SingleFilter Class Reference
SingleFilter Class Reference
Public Member Functions
__construct ($field, $defaultValue, $table=null, $displayField=null)
getForm (array $filters=null, $data=null)
getWhereClause ()
isEmpty ()
setDefaultValue ($value)
Private Attributes
$defaultValue
$displayField
$field
$tableName
Detailed Description
Allows SQL statements to be filtered by a single value in a single field.
Author:
John Oren
Version:
1.0 December 30, 2007
Constructor & Destructor Documentation
SingleFilter::__construct ($ field, $ defaultValue, $ table = null, $ displayField = null)
Constructs a filter for a single MySQL Field
Parameters:
STRING $field The field to filter by.
MIXED $defaultValue The value to search for in the given field. Set to null for no filter effect.
STRING $table The name of the database table this filter should pull data from for form display.
STRING $displayField The field used for display in the filter form.
References $defaultValue, $displayField, and $field.
Member Function Documentation
SingleFilter::getForm (array $ filters = null, $ data = null)
This type of filter does not have a form. Note that filter forms must define multiple field values as an array of values.
Parameters:
ARRAY $filters Array of Filter objects to use to filter a SQL query to get data for this form.
MIXED $data Optional data to use in this form.
Returns:
STRING Select box or error message.
Reimplemented from Filter.
References $data, $form, $result, $row, DatabaseManager::checkError(), DatabaseManager::fetchArray(), and Filter::getFilterClause().
SingleFilter::getWhereClause ()
Returns a formatted MySQL WHERE clause.
Returns:
STRING Formatted string for use in a MySQL query
Reimplemented from Filter.
SingleFilter::isEmpty ()
Returns whether or not this filter has a value to use to alter a database query.
Returns:
BOOLEAN True if this field can create a meaningful where clause
Reimplemented from Filter.
SingleFilter::setDefaultValue ($ value)
Sets the default value for this filter. Intended for use with this filter's form.
Parameters:
MIXED $value The value to use for this filter's where clause. Set to null for no filter effect.
Returns:
VOID
Reimplemented from Filter.
Member Data Documentation
SingleFilter::$defaultValue [private]
Referenced by __construct().
SingleFilter::$displayField [private]
Referenced by __construct().
SingleFilter::$field [private]
Referenced by __construct().
SingleFilter::$tableName [private]
The documentation for this class was generated from the following file:
OpenSiteAdmin/scripts/classes/Filters/SingleFilter.php