'TOME': ProcessBookAssociationHook Class Reference
ProcessBookAssociationHook Class Reference
Public Member Functions
__construct (Fieldset $fieldset, Field $keyField, Field $linkField, array $book)
process ()
Protected Attributes
$fieldset
$keyField
$linkField
$book
Constructor & Destructor Documentation
ProcessBookAssociationHook::__construct (Fieldset $ fieldset, Field $ keyField, Field $ linkField, array $ book)
Member Function Documentation
ProcessBookAssociationHook::process ()
Initiates custom processing for this hook.
Returns:
VOID
Implements hook.
References $_SERVER, $result, $row, $tmp, Form::ADD, DatabaseManager::checkError(), Form::EDIT, DatabaseManager::fetchAssoc(), DatabaseManager::getNumResults(), and print.
Member Data Documentation
ProcessBookAssociationHook::$book [protected]
ProcessBookAssociationHook::$fieldset [protected]
ProcessBookAssociationHook::$keyField [protected]
ProcessBookAssociationHook::$linkField [protected]
The documentation for this class was generated from the following file:
admin/scripts/functions.php