'TOME': Field Class Reference
Field Class Reference
Public Member Functions
__construct ($name, $title, $options, $inList, $required=false)
addAjax (Ajax $ajax)
appendDBErrors ()
databasePrep ()
display ()
getCSSID ()
getFieldName ()
getListView ($default)
getName ()
getTitle ($isList=false)
getValue ()
isDelete ()
isEmpty ()
isInList ()
isKey ()
isRequired ()
isSilent ()
process ()
setCSSID ($cssID)
setFormType ($formType)
setKey ()
setSilent ($silent)
setValue ($value)
__clone ()
Protected Member Functions
getErrorText ()
getOptions ()
postProcess ($value)
setEmpty ($value)
Protected Attributes
$ajax
$cssID
$errorText
$fieldName
$formType
$inList
$isEmpty
$name
$options
$required
$silent
$title
$value
Static Protected Attributes
static $nextFieldName = 0
Private Attributes
$keyField
Detailed Description
Handles form field display and pre-processing.
Sets up a form field for display, handling field and error display. Performs pre-processing on a form field, preparing it for use in a database.
Author:
John Oren
Version:
1.5 December 24, 2009
Constructor & Destructor Documentation
Field::__construct ($ name, $ title, $ options, $ inList, $ required = false)
Constructs a form field with information on how to display it.
Parameters:
STRING $name The name of the database field this form field corresponds to.
STRING $title The title to display for this form field.
MIXED $options The options associated with this form field.
BOOLEAN $inList True if this field should be used in a list view.
BOOLEAN $required True if this form field is required.
Reimplemented in SemesterPicker, ForeignKey, Password, and SessionText.
References $inList, $name, $options, $required, $title, and isEmpty().
Member Function Documentation
Field::__clone ()
Copies this field and gives it a new unique fieldname.
Returns:
VOID
Field::addAjax (Ajax $ ajax)
Sets the Ajax object associated with this field.
Parameters:
OBJECT Ajax object
Returns:
VOID
References getFieldName(), and Ajax::setFieldName().
Field::appendDBErrors ()
Appends errors that resulted from DB processing, such as collisions on unique keys.
Returns:
VOID
References getName().
Field::databasePrep ()
Hack to allow foreign keys to process correctly if they are called before their associated key gets processed.
Returns:
BOOLEAN False if unsuccessful
Reimplemented in ForeignKey.
Field::display () [abstract]
Prepares a form field for display.
Returns:
STRING HTML to display for the form field
Reimplemented in Checkbox, Date, ForeignKey, Group, Hidden, Image, Label, Password, RadioButtons, Select, SessionText, Text, and TextArea.
Field::getCSSID ()
Returns the name of the CSS ID for this field.
Returns:
STRING
Referenced by RadioButtons::display().
Field::getErrorText () [protected]
Returns any error text associated with this field.
Returns:
STRING Error messages.
References isSilent().
Referenced by TextArea::display(), Text::display(), Select::display(), RadioButtons::display(), Password::display(), Label::display(), Image::display(), Hidden::display(), Group::display(), ForeignKey::display(), Date::display(), Checkbox::display(), and SessionText::show().
Field::getFieldName ()
Returns the name of this field for use in an html form.
Returns:
STRING form field name.
Referenced by addAjax(), Fieldset::addField(), TextArea::display(), Text::display(), Select::display(), RadioButtons::display(), Password::display(), Label::display(), Image::display(), Hidden::display(), Group::display(), ForeignKey::display(), Date::display(), Checkbox::display(), ListManager::generateList(), TextArea::process(), Text::process(), Password::process(), Image::process(), Hidden::process(), Group::process(), Date::process(), Checkbox::process(), and process().
Field::getListView ($ default)
Returns the contents of this field for display in a list.
Parameters:
STRING The default value to use for this field in a list.
Returns:
STRING The default value.
Reimplemented in Checkbox, Image, Password, and Select.
Field::getName ()
Returns the name of the SQL field this form field is associated with.
Returns:
STRING The name of this form field's corresponding SQL field.
Referenced by Fieldset::addField(), appendDBErrors(), ListManager::generateList(), and Password::postProcess().
Field::getOptions () [protected]
Returns the options and flags for this form field.
Returns:
MIXED Options for this form field.
Referenced by TextArea::display(), Text::display(), Select::display(), RadioButtons::display(), Label::display(), Image::display(), Group::display(), ForeignKey::display(), Image::getListView(), Text::process(), Image::process(), Group::process(), ForeignKey::process(), and ISBNField::process().
Field::getTitle ($ isList = false)
Returns the display name (title) of this form field.
Parameters:
BOOLEAN $isList Excludes the visual queue for required fields in list view
Returns:
STRING The name to display with this form field.
Reimplemented in Hidden.
References isRequired().
Field::getValue ()
Gets the current value of this form field.
Returns:
MIXED Current field value.
Reimplemented in Password.
References SecurityManager::formPrep().
Referenced by TextArea::display(), Text::display(), Select::display(), RadioButtons::display(), Label::display(), Image::display(), Hidden::display(), Group::display(), Date::display(), Checkbox::display(), Image::process(), LETUEmailField::process(), ISBNField::process(), and ClassIDField::process().
Field::isDelete ()
Returns true if the type of the form this field is in is a delete form.
Returns:
BOOLEAN True if this field is in a delete form.
References Form::DELETE.
Referenced by TextArea::display(), Text::display(), Select::display(), RadioButtons::display(), Password::display(), Image::display(), Checkbox::display(), and Image::process().
Field::isEmpty ()
Returns true if this field does not have a value.
Returns:
BOOLEAN False if a value was provided.
Referenced by __construct(), TextArea::process(), Text::process(), SessionText::process(), Password::process(), Image::process(), Group::process(), Date::process(), Checkbox::process(), process(), Group::setEmpty(), and setEmpty().
Field::isInList ()
Returns whether or not this form field should be used in a list context.
Returns:
BOOLEAN True if this field should be displayed in a list view.
Field::isKey ()
Returns whether or not this field is associated with a database key.
Returns:
BOOLEAN True if this field is associated with a database key.
Field::isRequired ()
Returns whether or not this form field must be filled in.
Returns:
BOOLEAN True if this field cannot be empty.
Referenced by getTitle(), TextArea::process(), Text::process(), Password::process(), Image::process(), Group::process(), Date::process(), Checkbox::process(), and process().
Field::isSilent ()
Returns true if this field is currently suppressing error messages.
Returns:
BOOLEAN False if error messages are currently being displayed for this field.
Referenced by getErrorText().
Field::postProcess ($ value) [protected]
Post-processes the field (sets the fields value internally and in the database).
Parameters:
MIXED $value Value to store.
Returns:
BOOLEAN False if any error were encountered.
Reimplemented in Password.
References $value, setValue(), and SecurityManager::SQLPrep().
Referenced by TextArea::process(), Text::process(), Image::process(), Hidden::process(), Group::process(), Date::process(), Checkbox::process(), and process().
Field::process ()
Processes the field.
Returns:
BOOLEAN False if errors were encountered processing the field
Reimplemented in ClassIDField, ISBNField, LETUEmailField, Checkbox, Date, ForeignKey, Group, Hidden, Image, Password, SessionText, Text, and TextArea.
References $value, getFieldName(), isEmpty(), isRequired(), postProcess(), and setEmpty().
Field::setCSSID ($ cssID)
Sets the name of the CSS ID of this field.
Parameters:
STRING The new CSS ID.
Returns:
VOID
References $cssID.
Field::setEmpty ($ value) [protected]
Internal function to evaluate if this field is empty and set the empty flag accordingly.
Parameters:
MIXED $value Value (or values to check)
Returns:
VOID
Reimplemented in Group.
References $value, and isEmpty().
Referenced by TextArea::process(), Text::process(), Hidden::process(), ForeignKey::process(), Date::process(), Checkbox::process(), and process().
Field::setFormType ($ formType)
Sets the form this field is in.
Parameters:
INTEGER $formType A reference to the form this field is part of.
Returns:
VOID
References $formType.
Referenced by Fieldset::addField().
Field::setKey ()
Makes this field a database key.
Returns:
VOID
Referenced by ForeignKey::__construct().
Field::setSilent ($ silent)
Toggles error message suppression for this field.
Parameters:
BOOLEAN $silent True if errors should be suppressed.
Returns:
VOID
References $silent.
Referenced by Fieldset::addField().
Field::setValue ($ value)
Sets the value of this field in the database.
Parameters:
MIXED $value Value to set.
Returns:
VOID
References $value.
Referenced by Fieldset::addField(), Password::postProcess(), postProcess(), Image::process(), ForeignKey::process(), Date::process(), and LETUEmailField::process().
Member Data Documentation
Field::$ajax [protected]
Field::$cssID [protected]
Referenced by setCSSID().
Field::$errorText [protected]
Referenced by Checkbox::process().
Field::$fieldName [protected]
Field::$formType [protected]
Referenced by setFormType().
Field::$inList [protected]
Referenced by SessionText::__construct(), Password::__construct(), ForeignKey::__construct(), __construct(), and SemesterPicker::__construct().
Field::$isEmpty [protected]
Field::$keyField [private]
Field::$name [protected]
Referenced by SessionText::__construct(), Password::__construct(), ForeignKey::__construct(), __construct(), SemesterPicker::__construct(), and Image::isCorrectType().
Field::$nextFieldName = 0 [static, protected]
Field::$options [protected]
Referenced by SessionText::__construct(), Password::__construct(), ForeignKey::__construct(), __construct(), TextArea::display(), Text::display(), Image::display(), Group::display(), Image::getListView(), Text::process(), Image::process(), and Group::process().
Field::$required [protected]
Referenced by SessionText::__construct(), Password::__construct(), ForeignKey::__construct(), __construct(), and SemesterPicker::__construct().
Field::$silent [protected]
Referenced by setSilent().
Field::$title [protected]
Referenced by SessionText::__construct(), Password::__construct(), ForeignKey::__construct(), __construct(), and SemesterPicker::__construct().
Field::$value [protected]
Referenced by TextArea::display(), Select::display(), RadioButtons::display(), Label::display(), Group::display(), Date::display(), Checkbox::display(), Password::postProcess(), postProcess(), TextArea::process(), Text::process(), Image::process(), Hidden::process(), Group::process(), ForeignKey::process(), Date::process(), Checkbox::process(), process(), LETUEmailField::process(), ISBNField::process(), Group::setEmpty(), setEmpty(), and setValue().
The documentation for this class was generated from the following file:
OpenSiteAdmin/scripts/classes/Field.php