'TOME': Fieldset Class Reference
Fieldset Class Reference
Public Member Functions
__construct ($formType, $showLabels=true, $silent=false)
addField (Field $field, $default=null)
addFields (array $fields)
addRowManager (RowManager $dbRow)
commit ()
display ()
getFields ()
getTableName ()
getValue ($field)
getValues ()
getDBValues ()
isAdd ()
isEmpty ()
init ()
process ()
setFormType ($formType)
__toString ()
Protected Attributes
$dbRows
$fields
$formType
$isEmpty
$showLabels
$silent
$values
Detailed Description
Provides a template for creating HTML forms.
Handles display and processing of a group of form fields interfacing with a single row in a database.
Author:
John Oren
Version:
1.4 August 4, 2008
Constructor & Destructor Documentation
Fieldset::__construct ($ formType, $ showLabels = true, $ silent = false)
Constructs a new fieldset in the given form with no fields.
Parameters:
INTEGER $formType The form this fieldset is part of.
BOOLEAN $showLables If true, field titles are shown.
BOOLEAN $silent See comments on class member $silent.
References $formType, $showLabels, $silent, and isEmpty().
Member Function Documentation
Fieldset::__toString ()
Provides a friendly name for this class for error messages.
Returns:
STRING class name.
Fieldset::addField (Field $ field, $ default = null)
Adds a field to this fieldset.
Parameters:
OBJECT $field The object of type Field to add.
MIXED $default Optional default value for this field
Returns:
STRING The form name for this field.
References Field::getFieldName(), Field::getName(), Field::setFormType(), Field::setSilent(), and Field::setValue().
Referenced by addFields().
Fieldset::addFields (array $ fields)
Adds an array of fields to this fieldset by calling addField() on each field.
Parameters:
ARRAY $fields Array of field objects to add
Returns:
VOID
References $field, and addField().
Fieldset::addRowManager (RowManager $ dbRow)
Adds a row manager that the fields in this fieldset can use to interface with the database.
Parameters:
OBJECT $dbRow The database row manager object of type RowManager to add.
Returns:
VOID
References $field, Form::ADD, and getDBValues().
Fieldset::commit () [final]
Updates the database with values generated during the process stage.
If the row is empty and error suppression is on, the commit succeeds, though nothing actually happens.
Returns:
BOOLEAN False if an error was encountered updating the database.
References $error, $field, $name, Form::DELETE, ErrorLogManager::FATAL, init(), isEmpty(), ErrorLogManager::log(), and print.
Fieldset::display () [abstract]
Displays a form's row data as HTML.
Returns:
VOID
Reimplemented in Fieldset_Horizontal, and Fieldset_Vertical.
Fieldset::getDBValues ()
Fetches an array of key-value pairs of the form [fieldName]->value from the database.
Returns:
ARRAY Array of values in the database.
References $row, and $tmp.
Referenced by addRowManager(), init(), and process().
Fieldset::getFields ()
Returns an array of all the fields currently managed by this fieldset.
Returns:
ARRAY List of field objects
Referenced by ListManager::generateList().
Fieldset::getTableName ()
Returns the name of the first database table in the list.
Returns:
STRING A database table name associated with these fields.
Referenced by ListManager::generateList().
Fieldset::getValue ($ field)
Returns the current value of the given field (as understood by the database).
Parameters:
STRING $field The name of the field to look up.
Returns:
STRING The database's understanding of the given fields current value.
References $field.
Fieldset::getValues ()
Returns the internal values array.
Returns:
ARRAY Array of field values.
Fieldset::init ()
Initializes the internal values and field values from the database
Returns:
VOID
References $field, and getDBValues().
Referenced by commit(), Fieldset_Vertical::display(), and Fieldset_Horizontal::display().
Fieldset::isAdd ()
Checks to see if the form this fieldset is in is an add type form.
Returns:
BOOLEAN True if the form is an add form.
References Form::ADD.
Fieldset::isEmpty ()
Returns true if none of the fields (except Keys and ForeignKeys) have data.
Returns:
BOOLEAN False if a field (not a Key or ForeignKey) has a value.
Referenced by __construct(), commit(), and process().
Fieldset::process () [final]
Processes all the fields in this fieldset.
Error suppression (silent mode) is also controlled here. If silent mode is enabled and a field (not a Key or ForeignKey) is not empty, silent mode is disabled for the fieldset and for all fields in this fieldset. Also note that the database is not altered in any way by this process.
Returns:
BOOLEAN False if this form had errors.
References $field, $values, getDBValues(), and isEmpty().
Fieldset::setFormType ($ formType)
Sets the type of the form this fieldset is in
Parameters:
INTEGER $formType The form this fieldset is part of.
Returns:
VOID
References $formType.
Member Data Documentation
Fieldset::$dbRows [protected]
Fieldset::$fields [protected]
Fieldset::$formType [protected]
Referenced by __construct(), and setFormType().
Fieldset::$isEmpty [protected]
Fieldset::$showLabels [protected]
Referenced by __construct(), and Fieldset_Horizontal::generate().
Fieldset::$silent [protected]
Referenced by __construct().
Fieldset::$values [protected]
Referenced by process().
The documentation for this class was generated from the following file:
OpenSiteAdmin/scripts/classes/Fieldset.php