'TOME': SecurityManager Class Reference
SecurityManager Class Reference
Public Member Functions
__construct ($page="", $mode="")
getBaseName ($url)
isPageVisible ($page)
isRowVisible ($pageSuffix)
setPermissions ()
validatePage ($page)
Static Public Member Functions
static encrypt ($string, $salt)
static formPrep ($string)
static generateSalt ()
static getAccessLevels ()
static SQLPrep ($string)
Private Attributes
$errorMessages
$permissions
Detailed Description
Provides permission checking and encryption methods for the site.
Author:
John Oren
Version:
1.3 July 31, 2008
Constructor & Destructor Documentation
SecurityManager::__construct ($ page = "", $ mode = "")
Sets up the security manager with access to a database and an optional page to check permissions on.
Parameters:
STRING $page The name of a page to check.
STRING $mode An optional suffix to add to the page name, such as Add, Edit, or Delete.
References $mode, $page, setPermissions(), and validatePage().
Member Function Documentation
static SecurityManager::encrypt ($ string, $ salt) [static]
Encrypts the given string using the specified hashing algorithm. See the end of /OpenSiteAdmin/scripts/php.php for a list of available hashing algorithms. If the first option provided in this method is not available, try the algorithms in order from top to bottom for maximum security. The md5 function is provided as a last resort and is not recommended for applications needing to withstand organized security threats in future years.
Parameters:
STRING $string The string to encrypt.
STRING $salt Salt to use on the given string
Returns:
STRING Encrypted text (usually significantly longer than the input text).
Referenced by LoginManager::login(), and Password::process().
static SecurityManager::formPrep ($ string) [static, final]
Removes formatting added by SQLPrep.
Parameters:
STRING String to be formatted
Returns:
STRING Formatted string with formatting from SQLPrep removed
Referenced by RowManager::getValue(), Password::getValue(), and Field::getValue().
static SecurityManager::generateSalt () [static]
Generates a pseudo-random string for use with password hashing.
Returns:
STRING A pseudo-random 32 character string.
Referenced by LoginManager::login(), and Password::process().
static SecurityManager::getAccessLevels () [static]
Returns an array keyed by a user level's access level with values for the name of the particular access level.
Returns:
ARRAY $ret[levelNum] = levelName
SecurityManager::getBaseName ($ url)
Acts like PHP's basename($url, ".php") function, but also strips off any _GET variables in the URL.
Parameters:
STRING $url URL to process.
Returns:
STRING page name (no path information, no file extension, no _GET variable or anchor (#) information).
Referenced by isPageVisible().
SecurityManager::isPageVisible ($ page)
Verifies that the current user is allowed to view the specified page.
Parameters:
STRING $page The page to check permissions for.
Returns:
BOOLEAN False if the user is not allowed to view the page or exits with an error message if the page has no permissions.
References $_SERVER, $_SESSION, $page, and getBaseName().
Referenced by addPageLink(), and validatePage().
SecurityManager::isRowVisible ($ pageSuffix)
Verifies that the current user is allowed to view at least one of an add, edit, or delete page.
Parameters:
STRING $pageSuffix Suffix for add, edit, and delete (ex. add$pageSuffix).
Returns:
BOOLEAN False if the current user is not allowed to view the specified 'row' of pages.
References $_SESSION, and $page.
SecurityManager::setPermissions ()
Sets arrays of permission levels and error messages corresponding to the keys from getAccessLevels() for every page registered with the system.
Returns:
VOID
References $permissions, $result, $row, DatabaseManager::checkError(), and DatabaseManager::fetchAssoc().
Referenced by __construct().
static SecurityManager::SQLPrep ($ string) [static, final]
Formats a string for entry into a SQL database.
Parameters:
STRING String to be formatted
Returns:
MIXED If succesful, a formatted string ready for insertion into a SQL database If errors, an array of error messages
References DatabaseManager::getLink().
Referenced by ErrorLogManager::log(), LoginManager::login(), Password::postProcess(), Field::postProcess(), SessionText::process(), and RowManager::setValue().
SecurityManager::validatePage ($ page)
Checks if a page is visible. If it is not visible, redirects the user to the site's login page.
Parameters:
STRING $page The page to check permissions for.
Returns:
VOID Redirects the user if they cannot access the specified page.
References $_GET, $_SERVER, $_SESSION, $page, $path, $redir, and isPageVisible().
Referenced by __construct().
Member Data Documentation
SecurityManager::$errorMessages [private]
SecurityManager::$permissions [private]
Referenced by setPermissions().
The documentation for this class was generated from the following file:
OpenSiteAdmin/scripts/classes/SecurityManager.php