'TOME': Filter Class Reference
Filter Class Reference
Public Member Functions
getForm (array $filters=null, $data=null)
getWhereClause ()
isEmpty ()
setDefaultValue ($value)
Static Public Member Functions
static getFilterClause (array $filters=null)
Detailed Description
Defines a template for creating filters to generate SQL WHERE clauses.
Author:
John Oren
Version:
1.1 August 5, 2008
Member Function Documentation
static Filter::getFilterClause (array $ filters = null) [static, final]
Creates the MySQL where clause from all the given filters.
Parameters:
ARRAY $filters Filters to use in constructing the where clause.
Returns:
STRING MySQL where clause or an empty string if no filters were specified.
Referenced by RowManager::delete(), ListManager::generateList(), SingleFilter::getForm(), RowManager::getRowManagers(), RowManager::initialize(), and RowManager::update().
Filter::getForm (array $ filters = null, $ data = null) [abstract]
Returns an HTML form for display a filter for a list. Note that filter forms must define multiple field values as an array of values.
Parameters:
ARRAY $filters Array of Filter objects to use to filter a SQL query to get data for this form.
MIXED $data Optional data to use in this form.
Returns:
STRING HTML to display for the filter form.
Reimplemented in SingleFilter.
Filter::getWhereClause () [abstract]
Returns a formatted MySQL WHERE clause.
Returns:
STRING Formatted string for use in a MySQL query
Reimplemented in SingleFilter.
Filter::isEmpty () [abstract]
Returns whether or not this filter has a value to use to alter a database query.
Returns:
BOOLEAN True if this field can create a meaningful where clause
Reimplemented in SingleFilter.
Filter::setDefaultValue ($ value) [abstract]
Sets the default value for this filter.
Parameters:
MIXED $value The value or values to use for this filter's where clause
Returns:
VOID
Reimplemented in SingleFilter.
The documentation for this class was generated from the following file:
OpenSiteAdmin/scripts/classes/Filter.php