'TOME': ErrorLogManager Class Reference
ErrorLogManager Class Reference
Static Public Member Functions
static log ($msg, $errorType)
Public Attributes
const FATAL = 3
const ERROR = 7
const WARNING = 10
const INFO = 15
Detailed Description
Handles an error log for this site.
Sets up an error log if none exists and handles error logging for this system.
Author:
John Oren
Version:
1.0 December 30, 2007
Member Function Documentation
static ErrorLogManager::log ($ msg, $ errorType) [static, final]
Enters the given error message into the database's error log. Creates the error log if it does not exist.
Parameters:
STRING $msg Error message to store.
INTEGER $errorType Type of the error message (corresponding to a constant in this class).
Returns:
VOID
References DatabaseManager::checkError(), print, and SecurityManager::SQLPrep().
Referenced by DatabaseManager::checkError(), Fieldset::commit(), RowManager::delete(), Image::deleteFile(), TextArea::display(), RowManager::getModeText(), DatabaseManager::multiCheckError(), Image::process(), and RowManager::update().
Member Data Documentation
const ErrorLogManager::ERROR = 7
const ErrorLogManager::FATAL = 3
Referenced by DatabaseManager::checkError(), Fieldset::commit(), RowManager::delete(), Image::deleteFile(), TextArea::display(), RowManager::getModeText(), DatabaseManager::multiCheckError(), Image::process(), and RowManager::update().
const ErrorLogManager::INFO = 15
const ErrorLogManager::WARNING = 10
The documentation for this class was generated from the following file:
OpenSiteAdmin/scripts/classes/ErrorLogManager.php