'TOME': LoginManager Class Reference
LoginManager Class Reference
Public Member Functions
login ($user, $pass, $remember="no", $isCookie=false)
getUserID ()
suspend ($user)
Public Attributes
const MAX_LOGIN_ATTEMPTS = 5
const INVALID = 1
const NONE = 2
const SUSPENDED = 3
const UNKNOWN = 4
Protected Attributes
$userID
Detailed Description
Handles processing and security for the site's login process.
Author:
John Oren
Version:
1.2 July 31, 2008
Member Function Documentation
LoginManager::getUserID ()
Returns the primary key for the current user
Returns:
INT
LoginManager::login ($ user, $ pass, $ remember = "no", $ isCookie = false)
Attempts to log a user into the site's administrative system.
Parameters:
STRING $user Username to use to login.
STRING $pass Password to attempt to use with the given user.
STRING $remember If set to "yes", the user's login information will be saved in cookies if it validates sucessfully.
BOOLEAN $isCookie True if the provided data is coming from cookie data (cookie passwords are already encrypted).
Returns:
INTEGER One of the error code constants defined in this class.
References $_SESSION, $result, $row, $sql, DatabaseManager::checkError(), SecurityManager::encrypt(), DatabaseManager::fetchAssoc(), SecurityManager::generateSalt(), DatabaseManager::getNumResults(), INVALID, NONE, SecurityManager::SQLPrep(), SUSPENDED, and UNKNOWN.
LoginManager::suspend ($ user)
Attempts to suspend the account associated with the given username.
Parameters:
STRING $user Username for the account to suspend.
Returns:
VOID
References $result, $row, $sql, DatabaseManager::checkError(), DatabaseManager::fetchAssoc(), and DatabaseManager::getNumResults().
Member Data Documentation
LoginManager::$userID [protected]
const LoginManager::INVALID = 1
Referenced by login().
const LoginManager::MAX_LOGIN_ATTEMPTS = 5
const LoginManager::NONE = 2
Referenced by login().
const LoginManager::SUSPENDED = 3
Referenced by login().
const LoginManager::UNKNOWN = 4
Referenced by login().
The documentation for this class was generated from the following file:
OpenSiteAdmin/scripts/classes/LoginManager.php