'TOME': Image Class Reference
Image Class Reference
Public Member Functions
display ()
getListView ($default)
process ()
Protected Member Functions
isCorrectType ($name, $exts)
Static Protected Attributes
static $maxSize = 5120000
Private Member Functions
deleteFile ($file)
Detailed Description
Handles display and processing for an Image field.
Allows an image to be uploaded, verifying the file extention, checking file size limitations, and ensuring that each database entry references a unique file (to facilitate cleanup when deleting entries without the overhead of a reference counter). $options["path"] - Full path (relative or absolute) to the directory to save uploaded images to. $options["ext"] - Comma delimited list of valid file extensions (3 or 4 letters maximum). $options["width"] - Width of the image shown as a preview of the uploaded image. $options["height"]- Height of the image shown as a preview of the uploaded image.
Author:
John Oren
Version:
1.1 August 4, 2008
Member Function Documentation
Image::deleteFile ($ file) [private]
Attempts to delete the given file.
Parameters:
STRING $file The full name and path (relative or absolute) of the file to delete.
Returns:
BOOLEAN
References $file, ErrorLogManager::FATAL, and ErrorLogManager::log().
Referenced by process().
Image::display ()
Prepares this form field for display.
Returns:
STRING HTML to display for the form field
Reimplemented from Field.
References Field::$options, Field::getErrorText(), Field::getFieldName(), Field::getOptions(), Field::getValue(), isCorrectType(), and Field::isDelete().
Image::getListView ($ default)
Returns the contents of this field for display in a list.
Parameters:
STRING $default Default value to use.
Returns:
STRING Current field value to use in a list.
Reimplemented from Field.
References Field::$options, and Field::getOptions().
Image::isCorrectType ($ name, $ exts) [protected]
Checks to ensure that the given file name has a file extension in the provided list of valid extensions
Parameters:
STRING $name Name of the file to check.
ARRAY $exts Array of valid extensions (3 or 4 letters).
Returns:
BOOLEAN False if the given filename has an invalid file extension.
References Field::$name.
Referenced by display(), and process().
Image::process ()
Processes this field and update the backend used by this field.
Uploaded images will be in the following format: $file['name'] - The original name of the file on the client machine. $file['type'] - The mime type of the file, if the browser provided this information. An example would be "image/gif". This mime type is however not checked on the PHP side and therefore don't take its value for granted. $file['size'] - The size, in bytes, of the uploaded file. $file['tmp_name'] - The temporary filename of the file in which the uploaded file was stored on the server. $file['error'] - The error code associated with this file upload. See http://us2.php.net/manual/en/features.file-upload.errors.php for a list of error constants.
Returns:
BOOLEAN False if errors were encountered
Reimplemented from Field.
References $i, $maxSize, Field::$options, $path, Field::$value, deleteFile(), ErrorLogManager::FATAL, Field::getFieldName(), Field::getOptions(), Field::getValue(), isCorrectType(), Field::isDelete(), Field::isEmpty(), Field::isRequired(), ErrorLogManager::log(), Field::postProcess(), and Field::setValue().
Member Data Documentation
Image::$maxSize = 5120000 [static, protected]
Referenced by process().
The documentation for this class was generated from the following file:
OpenSiteAdmin/scripts/classes/Fields/Image.php