'TOME': RowManager Class Reference
RowManager Class Reference
Public Member Functions
__construct ($tableName, $primaryKeyName, $primaryKey=-1)
addFilter (Filter $filter, $group=false)
addFilters (array $filters)
finalize ($type)
getPrimaryKeyName ()
getRowManagers ()
getTableName ()
getValue ($fieldName)
getValues (array $fieldNames)
setOrderBy ($orderBy, $ascending=true)
setValue ($fieldName, $value, $update=true)
setValues (array $values)
sortAscending ($yes)
__toString ()
Static Public Member Functions
static getModeText ($mode)
Protected Member Functions
delete ()
getFilters ()
getLastInsertID ()
getPrimaryKeyFilter ()
getPrimaryKeyValue ()
initialize ()
insert ()
update ()
Protected Attributes
$filters
$hasValues
$orderBy
$primaryKeyName
$sortDir
$tableName
$updated
$values
Detailed Description
Handles database interaction with a row in a MySQL database table.
Author:
John Oren
Version:
1.6 January, 2009
Constructor & Destructor Documentation
RowManager::__construct ($ tableName, $ primaryKeyName, $ primaryKey = -1)
Constructs a new row manager with no fields, a unique ID, and the given data.
Parameters:
STRING $tableName Name of the table this row corresponds to.
STRING $primaryKeyName The name of the primary key field for this table.
INTEGER $primaryKey The value of the primary key for this row (if any)
References $primaryKeyName, $tableName, and initialize().
Member Function Documentation
RowManager::__toString ()
Returns the name of this class (for debug messages).
Returns:
STRING Class name.
RowManager::addFilter (Filter $ filter, $ group = false)
Adds the given filter to the internal list of query filters.
Parameters:
OBJECT $filter The filter object to add.
BOOLEAN $group Set to true to disable reinitialization. Used for optimizing imports of lists of filters.
Returns:
VOID
References initialize().
Referenced by addFilters().
RowManager::addFilters (array $ filters)
Adds the given list of filters to the internal list of query filters.
Parameters:
ARRAY $filters List of filters to add.
References addFilter(), and initialize().
RowManager::delete () [protected]
Deletes this row from the database.
Returns:
BOOLEAN False if errors where encountered in any field or in processing the form.
References $query, DatabaseManager::checkError(), ErrorLogManager::FATAL, Filter::getFilterClause(), getFilters(), getPrimaryKeyValue(), ErrorLogManager::log(), and print.
RowManager::finalize ($ type)
Updates the current data to the database, adding, inserting, or deleting as necessary.
Parameters:
INTEGER The type of this form for deciding whether to add, update, or delete.
Returns:
BOOLEAN False if an error is encountered.
References Form::DELETE, getModeText(), getPrimaryKeyValue(), and insert().
RowManager::getFilters () [protected]
Returns an array of all the filters associated with this object. If a primary key value has been set for this row, the primary key filter is added to the list of filters.
Returns:
ARRAY List of filter objects.
References $filters, getPrimaryKeyFilter(), and getPrimaryKeyValue().
Referenced by delete(), initialize(), and update().
RowManager::getLastInsertID () [protected]
Returns the last number used in an autoincrement field in this table.
Returns:
INTEGER Last insert ID number (usually the primary key)
References DatabaseManager::getInsertID().
Referenced by insert().
static RowManager::getModeText ($ mode) [static]
Returns the textual representation for a given mode constant.
Parameters:
INTEGER $mode One of the mode constants defined in this class.
Returns:
STRING Text corresponding to the given mode.
References $error, $mode, Form::ADD, Form::DELETE, Form::EDIT, ErrorLogManager::FATAL, ErrorLogManager::log(), and print.
Referenced by finalize().
RowManager::getPrimaryKeyFilter () [protected]
Returns a filter to limit a query to data pertaining to this row.
Returns:
OBJECT Filter object.
References getPrimaryKeyName(), and getPrimaryKeyValue().
Referenced by getFilters().
RowManager::getPrimaryKeyName ()
Returns the name of the primary key field for the table this row interacts with.
Returns:
STRING Primary key field name.
Referenced by Fieldset_Horizontal::generate(), getPrimaryKeyFilter(), getPrimaryKeyValue(), and getRowManagers().
RowManager::getPrimaryKeyValue () [protected]
Returns the value of this row's primary key.
Returns:
MIXED Primary key value.
References getPrimaryKeyName().
Referenced by delete(), finalize(), getFilters(), getPrimaryKeyFilter(), and update().
RowManager::getRowManagers ()
Returns a list of row managers for all the rows in this row manager's table matching the current filters.
It is highly recommended, but not required, that the user apply filters to this row manager before executing this method.
Returns:
ARRAY List of all row managers, one for each database row matching the query.
References $i, $result, $sql, DatabaseManager::checkError(), DatabaseManager::fetchAssoc(), Filter::getFilterClause(), and getPrimaryKeyName().
Referenced by Fieldset_Horizontal::generate().
RowManager::getTableName ()
Returns the name of the database table this row interacts with.
Returns:
STRING Name of this row's database table.
Referenced by Fieldset_Horizontal::generate(), and initialize().
RowManager::getValue ($ fieldName)
Returns the most recently available value for the given field ready for form display.
Parameters:
STRING $fieldName The name of the database field.
Returns:
MIXED The value of this field in memory
References SecurityManager::formPrep().
Referenced by getValues(), and setValue().
RowManager::getValues (array $ fieldNames)
Returns the most recently available value for the given fields ready for form display.
Parameters:
ARRAY $fieldNames An array keyed by the names of database fields.
Returns:
ARRAY The given array with populated values.
References getValue().
RowManager::initialize () [protected]
Initializes the array of values currently in the database for this row (if any).
Returns:
VOID
References $result, $sql, DatabaseManager::checkError(), DatabaseManager::fetchAssoc(), Filter::getFilterClause(), getFilters(), and getTableName().
Referenced by __construct(), addFilter(), and addFilters().
RowManager::insert () [protected]
Inserts the current set of values into the database.
Returns:
BOOLEAN False if errors where encountered in any field or in processing the form.
References $name, $query, $values, DatabaseManager::checkError(), getLastInsertID(), and setValue().
Referenced by finalize().
RowManager::setOrderBy ($ orderBy, $ ascending = true)
Sets the field name results should be ordered by.
Parameters:
STRING $orderBy The name of the database field to order by.
BOOLEAN $ascending Sorts ascending if true
Returns:
VOID
References $orderBy, and sortAscending().
RowManager::setValue ($ fieldName, $ value, $ update = true)
Sets the current local value for the given fieldname.
Parameters:
STRING $fieldName Name of the database field.
MIXED $value The value to set.
BOOLEAN $update If false, $this->updated is not altered. This is useful for fields like foreign keys that do not provide any new information unique to the row.
Returns:
VOID
References getValue(), and SecurityManager::SQLPrep().
Referenced by insert(), and setValues().
RowManager::setValues (array $ values)
Sets the internal value array using the given values if the array key (corresponding to the column name) is a column associated with this row manager
Parameters:
ARRAY $values Associative array of column=>value data
Returns:
VOID
References $field, and setValue().
RowManager::sortAscending ($ yes)
Changes the sort order of results
Parameters:
BOOLEAN $yes Sorts ascending if true
Returns:
VOID
Referenced by setOrderBy().
RowManager::update () [protected]
Updates the database with the current set of values if any changes have been made.
Returns:
BOOLEAN False if errors where encountered in any field or in processing the form.
References $name, $query, DatabaseManager::checkError(), ErrorLogManager::FATAL, Filter::getFilterClause(), getFilters(), getPrimaryKeyValue(), ErrorLogManager::log(), and print.
Member Data Documentation
RowManager::$filters [protected]
Referenced by getFilters().
RowManager::$hasValues [protected]
RowManager::$orderBy [protected]
Referenced by setOrderBy().
RowManager::$primaryKeyName [protected]
Referenced by __construct().
RowManager::$sortDir [protected]
RowManager::$tableName [protected]
Referenced by __construct().
RowManager::$updated [protected]
RowManager::$values [protected]
Referenced by insert().
The documentation for this class was generated from the following file:
OpenSiteAdmin/scripts/classes/RowManager.php