'TOME': admin/scripts/functions.php File Reference
functions.php File Reference
Classes
class CheckoutFormHook
class CheckoutForm
class ProcessBookAssociationHook
Functions
getBookAvailability ($id)
getISBN ($isbn13, $isbn10)
showBookInfo (array $book, $editable=true, $showID=false)
showCheckoutForm (array $checkout)
showCheckinForm (array $book)
getProcessISBNCheckoutFieldset ($bookTypeID)
getProcessBookAssociation (array $book)
redir_push ($str)
redir_pop ()
cleanSessionOnEmptyRedir ()
Function Documentation
cleanSessionOnEmptyRedir ()
References $_SESSION.
Referenced by checkout_update_hoook::process(), and update_hook::process().
getBookAvailability ($ id)
References $_SESSION, $id, $result, $row, $sql, DatabaseManager::checkError(), DatabaseManager::fetchArray(), and DatabaseManager::fetchAssoc().
Referenced by getProcessISBNCheckoutFieldset().
getISBN ($ isbn13, $ isbn10)
Referenced by showBookInfo().
getProcessBookAssociation (array $ book)
References $_SERVER, $_SESSION, $ajax, $fieldset, $form, $keyField, $linkField, and Form::EDIT.
getProcessISBNCheckoutFieldset ($ bookTypeID)
References $_SERVER, $_SESSION, $ajax, $fieldset, $form, $keyField, $linkField, $row, Form::ADD, and getBookAvailability().
redir_pop ()
References $_SESSION.
redir_push ($ str)
References $_SESSION.
Referenced by CheckoutFormHook::process().
showBookInfo (array $ book, $ editable = true, $ showID = false)
References $_SERVER, $isbn, getISBN(), php, and print.
showCheckinForm (array $ book)
References php.
showCheckoutForm (array $ checkout)
References $books, getAvailableBooksForISBN(), php, and print.