'TOME': management.php File Reference
management.php File Reference
Classes
class SemesterUpdateHook
Functions
getSemesters ()
Variables
$path = "./"
$pageTitle = "User & System Management"
$securityManager = new SecurityManager()
$form = new Form(Form::EDIT, $_SERVER["SCRIPT_NAME"])
$fieldset = new Fieldset_Vertical($form->getFormType())
$keyField = $fieldset->addField(new Hidden("ID", "", null, false))
$field = $fieldset->addField(new Select("semester", "Your Current Semester", getSemesters(), false))
$row = new RowManager("users", $keyField->getName(), $_SESSION["ID"])
$levels [1] = "Developer"
$levels [2] = "Administrator"
$levels [3] = "TOMEKeeper"
$result = DatabaseManager::checkError("select * from `libraries`")
$libraries = array()
$fields [] = new Password("password", "Password", null, false)
Function Documentation
getSemesters ()
References $year.
Variable Documentation
$field = $fieldset->addField(new Select("semester", "Your Current Semester", getSemesters(), false))
Referenced by Fieldset::addFields(), Fieldset::addRowManager(), Fieldset::commit(), Fieldset_Vertical::display(), Fieldset_Horizontal::display(), Fieldset_Horizontal::generate(), ListManager::generateList(), Fieldset::getValue(), Fieldset::init(), Fieldset::process(), checkout_update_hoook::process(), update_hook::process(), and RowManager::setValues().
$fields[] = new Password("password", "Password", null, false)
Referenced by ListManager::generateList().
$fieldset = new Fieldset_Vertical($form->getFormType())
if ($securityManager->isPageVisible("editSemester")) $form = new Form(Form::EDIT, $_SERVER["SCRIPT_NAME"])
while ($row=DatabaseManager::fetchAssoc($result)) $keyField = $fieldset->addField(new Hidden("ID", "", null, false))
$levels[3] = "TOMEKeeper"
$levels[2] = "Administrator"
$levels = "Developer"
Referenced by generateAccessTable().
$libraries = array()
$pageTitle = "User & System Management"
$path = "./"
$result = DatabaseManager::checkError("select * from `libraries`")
$row = new RowManager("users", $keyField->getName(), $_SESSION["ID"])
$securityManager = new SecurityManager()
Referenced by addPage().