'TOME': ForeignKey Class Reference
ForeignKey Class Reference
Public Member Functions
__construct ($name, $title, $options, $inList, $required=false)
databasePrep ()
display ()
process ()
Detailed Description
Handles display and processing for a ForeignKey field.
A foreign key gets its value from a key field which must be processed before this field. $option = Instance of class Field
Author:
John Oren
Version:
1.1 August 4, 2008
Constructor & Destructor Documentation
ForeignKey::__construct ($ name, $ title, $ options, $ inList, $ required = false)
Constructs a form field with information on how to display it.
Parameters:
STRING $name The name of the database field this form field corresponds to.
STRING $title The title to display for this form field.
MIXED $options The options associated with this form field.
BOOLEAN $inList True if this field should be used in a list view.
BOOLEAN $required True if this form field is required.
Reimplemented from Field.
References Field::$inList, Field::$name, Field::$options, Field::$required, Field::$title, and Field::setKey().
Member Function Documentation
ForeignKey::databasePrep ()
Hack to allow foreign keys to process correctly if they are called before their associated key gets processed.
Returns:
BOOLEAN False if unsuccessful
Reimplemented from Field.
References process().
ForeignKey::display ()
Prepares this form field for display.
Returns:
STRING HTML to display for the form field
Reimplemented from Field.
References Field::getErrorText(), Field::getFieldName(), and Field::getOptions().
ForeignKey::process ()
Processes this field and update the backend used by this field.
Returns:
BOOLEAN False if errors were encountered
Reimplemented from Field.
References Field::$value, Field::getOptions(), Field::setEmpty(), and Field::setValue().
Referenced by databasePrep().
The documentation for this class was generated from the following file:
OpenSiteAdmin/scripts/classes/Fields/ForeignKey.php