'TOME': Label Class Reference
Label Class Reference
Public Member Functions
display ()
Detailed Description
Handles display and processing of a Label field.
A label is like a hidden field, but it displays the value in the hidden field. There are no options for this field.
Author:
John Oren
Version:
1.1 August 4, 2008
Member Function Documentation
Label::display ()
Prepares this form field for display.
Returns:
STRING HTML to display for the form field
Reimplemented from Text.
References Field::$value, Field::getErrorText(), Field::getFieldName(), Field::getOptions(), and Field::getValue().
The documentation for this class was generated from the following file:
OpenSiteAdmin/scripts/classes/Fields/Label.php