'TOME': Group Class Reference
Group Class Reference
Public Member Functions
display ()
process ()
Protected Member Functions
setEmpty ($value)
Detailed Description
Handles display and processing for a Group field.
A group field is a set of fields that are combined together using a standard delimiter. Date fields are a good example of a group field (ex. month day year with a dilimter of '/') Page ranges are another example (start end with a delimiter of '-') $options["elements"] - number of individual fields to display $options["seperator"] - dilimiter for the fields $options["size"] - size of the form's text input fields OPTIONAL $options["maxlength"] - maximum length of text in any given input field $options["prefix"] - A prefix to prepend to the field data after it has been combined $options["suffix"] - A suffix to append to the field data after it has been combined
Author:
John Oren
Version:
1.1 August 4, 2008
Member Function Documentation
Group::display ()
Prepares this form field for display.
Returns:
STRING HTML to display for the form field
Reimplemented from Field.
References $i, Field::$options, Field::$value, Field::getErrorText(), Field::getFieldName(), Field::getOptions(), and Field::getValue().
Group::process ()
Processes this field and update the backend used by this field.
Returns:
BOOLEAN False if errors were encountered
Reimplemented from Field.
References $i, Field::$options, Field::$value, Field::getFieldName(), Field::getOptions(), Field::isEmpty(), Field::isRequired(), Field::postProcess(), and setEmpty().
Group::setEmpty ($ value) [protected]
Internal function to evaluate if this field is empty and set the empty flag accordingly.
Parameters:
MIXED $value Value (or values to check)
Returns:
VOID
Reimplemented from Field.
References Field::$value, and Field::isEmpty().
Referenced by process().
The documentation for this class was generated from the following file:
OpenSiteAdmin/scripts/classes/Fields/Group.php