'TOME': ListManager Class Reference
ListManager Class Reference
Public Member Functions
__construct ()
addFilter (Filter $filter)
generateList (Fieldset $fieldset, Field $keyField, Field $linkField, $QS, $data=null)
setOrderBy ($order, $ascending=true)
sortAscending ($yes)
Protected Member Functions
generateFilterForms ($filters, $data)
Protected Attributes
$filters
$order
$sortDir
Detailed Description
Manages processing and display for lists based on a row's database information.
Author:
John Oren
Version:
1.1 July 31, 2008
Constructor & Destructor Documentation
ListManager::__construct ()
Constructs a new list (does not initiate any display or processing).
Member Function Documentation
ListManager::addFilter (Filter $ filter)
Adds a filter to the list being displayed.
Parameters:
OBJECT $filter The object of type Filter to add.
Returns:
VOID
ListManager::generateFilterForms ($ filters, $ data) [protected]
Generates forms from any filters that may be applied to this form.
Parameters:
ARRAY $filters Array of filters to generate forms for.
ARRAY $data Form data to use to populate filter data.
Returns:
STRING HTML form to use for filtering the list.
References $data, and $filters.
Referenced by generateList().
ListManager::generateList (Fieldset $ fieldset, Field $ keyField, Field $ linkField, $ QS, $ data = null)
Generates and returns a list (HTML table) of data using the given row as a template.
Parameters:
OBJECT $fieldset Fieldset object to use as a template for fields and field titles.
OBJECT $keyField The primary key field for the provided fieldset.
OBJECT $linkField The database field to use as a link to allow for editing a particular field.
STRING $QS Any text to apply to the end of links. An '&' is prepended to this if it is not empty.
ARRAY $data Form data from filter forms.
Returns:
STRING HTML Table containing the list data.
References $data, $field, $fields, $order, $QS, $result, DatabaseManager::checkError(), DatabaseManager::fetchAssoc(), generateFilterForms(), Field::getFieldName(), Fieldset::getFields(), Filter::getFilterClause(), Field::getName(), and Fieldset::getTableName().
ListManager::setOrderBy ($ order, $ ascending = true)
Sets the MySQL ORDER BY clause (The phrase "ORDER BY" is automatically included).
Parameters:
STRING $order Name of the column to order the display by.
BOOLEAN $ascending Sorts ascending if true
Returns:
VOID
References $order, and sortAscending().
ListManager::sortAscending ($ yes)
Changes the sort order of results
Parameters:
BOOLEAN $yes Sorts ascending if true
Returns:
VOID
Referenced by setOrderBy().
Member Data Documentation
ListManager::$filters [protected]
Referenced by generateFilterForms().
ListManager::$order [protected]
Referenced by generateList(), and setOrderBy().
ListManager::$sortDir [protected]
The documentation for this class was generated from the following file:
OpenSiteAdmin/scripts/classes/ListManager.php