'TOME': DatabaseManager Class Reference
DatabaseManager Class Reference
Public Member Functions
changeUser ($user, $pass)
getDatabase ()
getLinkResource ()
getServer ()
getUser ()
selectDatabase ($db)
Static Public Member Functions
static checkError ($query)
static getInsertID ()
static getNumResults ()
static fetchArray ($result)
static fetchAssoc ($result)
static fetchAssocArray ($result)
static getLink ()
static multiCheckError ($query)
Protected Member Functions
__construct ($user=DB_USER, $pass=DB_PASS, $db=DB_NAME, $host=DB_ROOT)
Protected Attributes
$database
$server
$SQL
$username
Static Protected Attributes
static $dbObj
Detailed Description
Interfaces with the site database.
Provides an interface to connect to an interact with the database generally.
Author:
John Oren
Version:
2.0 December 21, 2009
Constructor & Destructor Documentation
DatabaseManager::__construct ($ user = DB_USER, $ pass = DB_PASS, $ db = DB_NAME, $ host = DB_ROOT) [protected]
Constructs a database manager with a link resource to a MySQL database.
Parameters:
STRING $user The username to use when connecting to the database.
STRING $pass The password to use for the given username.
STRING $db The name of the database to connect to.
STRING $host The name of the server to connect to.
Member Function Documentation
DatabaseManager::changeUser ($ user, $ pass)
Attempts to change the user used to connect to the database.
Parameters:
STRING $user The username to use when connecting to the database.
STRING $pass The password to use for the given username.
Returns:
BOOLEAN True if the new username and password were valid and the connection could be established to the current database.
static DatabaseManager::checkError ($ query) [static]
Checks for errors and runs the provided MySQL query.
Parameters:
STRING $query The MySQL query to run.
Returns:
BOOLEAN Query result or false if the row's error flag was set or if the query failed.
References $error, $query, $result, ErrorLogManager::FATAL, getLink(), ErrorLogManager::log(), and print.
Referenced by RowManager::delete(), fetchAssocArray(), generateAccessTable(), ListManager::generateList(), getBookAvailability(), SingleFilter::getForm(), RowManager::getRowManagers(), RowManager::initialize(), RowManager::insert(), ErrorLogManager::log(), LoginManager::login(), DeleteClassHook::process(), ProcessBookAssociationHook::process(), CheckoutFormHook::process(), SecurityManager::setPermissions(), LoginManager::suspend(), and RowManager::update().
static DatabaseManager::fetchArray ($ result) [static]
Wrapper for getting an array of the next row's data.
Parameters:
OBJECT The connection resource to reference.
Returns:
ARRAY the next row's data.
References $result.
Referenced by generateAccessTable(), getBookAvailability(), SingleFilter::getForm(), and CheckoutFormHook::process().
static DatabaseManager::fetchAssoc ($ result) [static]
Wrapper for getting an associative array of the next row's data.
Parameters:
OBJECT The connection resource to reference.
Returns:
ARRAY The next row's data in an associative array.
References $result.
Referenced by fetchAssocArray(), ListManager::generateList(), getBookAvailability(), RowManager::getRowManagers(), RowManager::initialize(), LoginManager::login(), ProcessBookAssociationHook::process(), SecurityManager::setPermissions(), and LoginManager::suspend().
static DatabaseManager::fetchAssocArray ($ result) [static]
Helper function for fetching all of the rows in the result set into an array of associative arrays.
Parameters:
MIXED Query resource or a raw query string
Returns:
ARRAY Array of associative arrays or an empty array if no results.
References $result, $row, checkError(), and fetchAssoc().
Referenced by getAvailableBooksForISBN().
DatabaseManager::getDatabase ()
Returns the name of the database this manager is currently connected to.
Returns:
STRING Currently used database name.
static DatabaseManager::getInsertID () [static]
Wrapper for getting the last insert ID
Returns:
MIXED false on failure, int on success.
References getLink().
Referenced by RowManager::getLastInsertID(), and CheckoutFormHook::process().
static DatabaseManager::getLink () [static]
Constructs an instance of the database manager if necessary and returns a link resource to the database.
Returns:
RESOURCE Link reource to the database.
References $dbObj.
Referenced by checkError(), getInsertID(), getNumResults(), multiCheckError(), selectDatabase(), and SecurityManager::SQLPrep().
DatabaseManager::getLinkResource ()
Returns a link resource to the database.
Returns:
RESOURCE Link resource to the database.
static DatabaseManager::getNumResults () [static]
Wrapper for getting the number of rows returned from a query.
Returns:
INT the number of rows in this result set
References getLink().
Referenced by LoginManager::login(), ProcessBookAssociationHook::process(), CheckoutFormHook::process(), and LoginManager::suspend().
DatabaseManager::getServer ()
Returns the name of the server this class is currently connected to.
Returns:
STRING Name of the server this class is currently connected to.
DatabaseManager::getUser ()
Returns the name of the user currently logged into the database.
Returns:
STRING Currently active user name.
static DatabaseManager::multiCheckError ($ query) [static]
Checks for errors and runs the provided MySQL queries. Currently does not support select statements
Parameters:
STRING $query The MySQL queries to run.
Returns:
BOOLEAN false if the row's error flag was set or if the query failed.
References $error, $query, $result, ErrorLogManager::FATAL, getLink(), ErrorLogManager::log(), and print.
DatabaseManager::selectDatabase ($ db)
Sets the database this database manager is currently connected to.
Parameters:
STRING $db The name of the database to connect to.
Returns:
VOID
References getLink().
Member Data Documentation
DatabaseManager::$database [protected]
DatabaseManager::$dbObj [static, protected]
Referenced by getLink().
DatabaseManager::$server [protected]
DatabaseManager::$SQL [protected]
DatabaseManager::$username [protected]
The documentation for this class was generated from the following file:
OpenSiteAdmin/scripts/classes/DatabaseManager.php