'TOME': Hidden Class Reference
Hidden Class Reference
Public Member Functions
display ()
getTitle ($isList=false)
process ()
Detailed Description
Handles display and processing of a Hidden field.
There are no options for this field.
Author:
John Oren
Version:
1.1 August 4, 2008
Member Function Documentation
Hidden::display ()
Prepares this form field for display.
Returns:
STRING HTML to display for the form field
Reimplemented from Field.
Reimplemented in SessionText.
References Field::getErrorText(), Field::getFieldName(), and Field::getValue().
Hidden::getTitle ($ isList = false)
Returns the display name (title) of this form field. Hidden fields should never reveal an asterisk, even if they are required
Parameters:
BOOLEAN $isList Excludes the visual queue for required fields in list view
Returns:
STRING The name to display with this form field.
Reimplemented from Field.
Hidden::process ()
Processes this field and update the backend used by this field.
Returns:
BOOLEAN False if errors were encountered
Reimplemented from Field.
Reimplemented in SessionText.
References Field::$value, Field::getFieldName(), Field::postProcess(), and Field::setEmpty().
The documentation for this class was generated from the following file:
OpenSiteAdmin/scripts/classes/Fields/Hidden.php