'TOME': CheckoutFormHook Class Reference
CheckoutFormHook Class Reference
Public Member Functions
__construct (Fieldset $fieldset, RowManager $row, Field $linkField, Field $patronIDField, $id, Field $libField=null)
process ()
Protected Member Functions
sendNotificationEmail ()
getMessageFooter ()
Protected Attributes
$fieldset
$row
$linkField
$patronIDField
$libField
$id
Constructor & Destructor Documentation
CheckoutFormHook::__construct (Fieldset $ fieldset, RowManager $ row, Field $ linkField, Field $ patronIDField, $ id, Field $ libField = null)
References $id, and $libField.
Member Function Documentation
CheckoutFormHook::getMessageFooter () [protected]
Referenced by sendNotificationEmail().
CheckoutFormHook::process ()
Initiates custom processing for this hook.
Note that if this function throws an exception, it will be caught and the page will not be redirected. Also, all hooks added after the failing hook will NOT be executed.
Returns:
VOID
Implements hook.
References $_SERVER, $_SESSION, $path, $result, $row, $sql, DatabaseManager::checkError(), DatabaseManager::fetchArray(), DatabaseManager::getInsertID(), DatabaseManager::getNumResults(), redir_push(), and sendNotificationEmail().
CheckoutFormHook::sendNotificationEmail () [protected]
References $comments, $libraryID, $result, $sql, DatabaseManager::checkError(), DatabaseManager::fetchAssoc(), and getMessageFooter().
Referenced by process().
Member Data Documentation
CheckoutFormHook::$fieldset [protected]
CheckoutFormHook::$id [protected]
Referenced by __construct().
CheckoutFormHook::$libField [protected]
Referenced by __construct().
CheckoutFormHook::$linkField [protected]
CheckoutFormHook::$patronIDField [protected]
CheckoutFormHook::$row [protected]
Referenced by process().
The documentation for this class was generated from the following file:
admin/scripts/functions.php