'TOME': Checkbox Class Reference
Checkbox Class Reference
Public Member Functions
display ()
getListView ($default)
process ()
Detailed Description
Handles display and processing for a Checkbox field.
There are no options for this field.
Author:
John Oren
Version:
1.2 August 4, 2008
Member Function Documentation
Checkbox::display ()
Prepares this form field for display.
Returns:
STRING HTML to display for the form field
Reimplemented from Field.
References Field::$value, Field::getErrorText(), Field::getFieldName(), Field::getValue(), and Field::isDelete().
Checkbox::getListView ($ default)
Gets the current value of this form field.
Parameters:
STRING $default Default value to use.
Returns:
STRING Current field value.
Reimplemented from Field.
Checkbox::process ()
Processes this field and update the backend used by this field.
Returns:
BOOLEAN False if errors were encountered
Reimplemented from Field.
References Field::$errorText, Field::$value, Field::getFieldName(), Field::isEmpty(), Field::isRequired(), Field::postProcess(), and Field::setEmpty().
The documentation for this class was generated from the following file:
OpenSiteAdmin/scripts/classes/Fields/Checkbox.php