'TOME': Select Class Reference
Select Class Reference
Public Member Functions
display ()
getListView ($default)
Detailed Description
Handles display and processing of a Select field.
The options parameter is an array of key-value pairs in the following format: $options[key] = value
Author:
John Oren
Version:
1.1 August 4, 2008
Member Function Documentation
Select::display ()
Prepares this form field for display.
Returns:
STRING HTML to display for the form field
Reimplemented from Field.
Reimplemented in RadioButtons.
References Field::$value, Field::getErrorText(), Field::getFieldName(), Field::getOptions(), Field::getValue(), and Field::isDelete().
Select::getListView ($ default)
Returns the contents of this field for display in a list.
Parameters:
STRING $default Default value to display.
Returns:
STRING Current field value to use in a list.
Reimplemented from Field.
The documentation for this class was generated from the following file:
OpenSiteAdmin/scripts/classes/Fields/Select.php