'TOME': SessionText Class Reference
SessionText Class Reference
Public Member Functions
__construct ($name, $title, $options, $inList, $required=false)
display ()
process ()
show ($defaultValue, $enabled=true)
Private Attributes
$keyName
Detailed Description
Handles processing of a truly hidden field tracked through session data.
There are no options for this field.
Author:
John Oren
Version:
1.0 August 4, 2008
Constructor & Destructor Documentation
SessionText::__construct ($ name, $ title, $ options, $ inList, $ required = false)
Constructs a form field with information on how to display it.
Parameters:
STRING $name The name of the database field this form field corresponds to.
STRING $title The title to display for this form field.
MIXED $options Ignored as there are no options for this field.
BOOLEAN $inList True if this field should be used in a list view.
BOOLEAN $required True if this form field is required.
Reimplemented from Field.
References Field::$inList, Field::$name, Field::$options, Field::$required, and Field::$title.
Member Function Documentation
SessionText::display ()
Prepares a form field for display.
Returns:
STRING HTML to display for the form field
Reimplemented from Hidden.
SessionText::process ()
Processes this field, updates the current value field, and returns formated data ready for insertion into a SQL database.
Returns:
STRING Formatted string ready for insertion into a SQL database
Reimplemented from Hidden.
References $_SESSION, Field::isEmpty(), and SecurityManager::SQLPrep().
SessionText::show ($ defaultValue, $ enabled = true)
Prepares this form field for display and stores the value being displayed.
Parameters:
STRING $defaultValue Default value to display in this form field
BOOLEAN $enabled True if this form field is editable
Returns:
STRING HTML to display for the form field
References $_SESSION, and Field::getErrorText().
Member Data Documentation
SessionText::$keyName [private]
The documentation for this class was generated from the following file:
OpenSiteAdmin/scripts/classes/Fields/SessionText.php