'TOME': ISBNField Class Reference
ISBNField Class Reference
Public Member Functions
process ()
Detailed Description
Handles display and processing of a Text field designed specifically to process ISBN numbers.
OPTIONAL
$options["size"] - size of the form's text input field
$options["maxlength"] - maximum length of text input field
Member Function Documentation
ISBNField::process ()
Processes this field and update the backend used by this field.
See also:
validateISBN()
Returns:
BOOLEAN False if errors were encountered
Reimplemented from Text.
References Field::$value, Field::getOptions(), Field::getValue(), and validateISBN().
The documentation for this class was generated from the following file:
admin/scripts/ISBNField.php