'TOME': Password Class Reference
Password Class Reference
Public Member Functions
__construct ($name, $title, $options, $inList, $required=false)
display ()
getListView ($default)
process ()
getValue ()
Protected Member Functions
postProcess ($value)
Detailed Description
Handles display and processing of a Password field.
There are no options for this field.
Author:
John Oren
Version:
1.1 August 4, 2008
Constructor & Destructor Documentation
Password::__construct ($ name, $ title, $ options, $ inList, $ required = false)
Constructs a password field with a two-line title for the password confirmation box.
Parameters:
STRING $name The name of the database field this form field corresponds to.
STRING $title The title to display for this form field.
MIXED $options Any options are ignored as this field has no options.
BOOLEAN $inList True if this field should be used in a list view.
BOOLEAN $required True if this form field is required.
Reimplemented from Field.
References Field::$inList, Field::$name, Field::$options, Field::$required, and Field::$title.
Member Function Documentation
Password::display ()
Prepares this form field for display.
Returns:
STRING HTML to display for the form field
Reimplemented from Field.
References Field::getErrorText(), Field::getFieldName(), and Field::isDelete().
Password::getListView ($ default)
Returns the contents of this field for display in a list.
Parameters:
STRING $default Default value to display
Returns:
STRING Current field value to use in a list.
Reimplemented from Field.
Password::getValue ()
Gets the current value of this form field.
Returns:
MIXED Current field value.
Reimplemented from Field.
References SecurityManager::formPrep().
Referenced by process().
Password::postProcess ($ value) [protected]
Post-processes the field (sets the fields value internally and in the database).
Parameters:
MIXED $value Value to store.
Returns:
BOOLEAN False if any error were encountered.
Reimplemented from Field.
References Field::$value, Field::getName(), Field::setValue(), and SecurityManager::SQLPrep().
Referenced by process().
Password::process ()
Processes this field and update the backend used by this field.
Returns:
BOOLEAN False if errors were encountered
Reimplemented from Field.
References SecurityManager::encrypt(), SecurityManager::generateSalt(), Field::getFieldName(), getValue(), Field::isEmpty(), Field::isRequired(), and postProcess().
The documentation for this class was generated from the following file:
OpenSiteAdmin/scripts/classes/Fields/Password.php