'TOME': Fieldset_Horizontal Class Reference
Fieldset_Horizontal Class Reference
Public Member Functions
display ()
Static Public Member Functions
static generate (RowManager $iterator, array $fields, Form $form, $numExtraRows=0)
Detailed Description
Handles display and processing for a list-style form.
Author:
John Oren
Version:
1.1 August 4, 2008
Member Function Documentation
Fieldset_Horizontal::display ()
Displays this form's row fields in a horizontal HTML form.
Returns:
VOID
Reimplemented from Fieldset.
References $field, Fieldset::init(), and print.
static Fieldset_Horizontal::generate (RowManager $ iterator, array $ fields, Form $ form, $ numExtraRows = 0) [static]
Generates multiple rows as a group.
Displays multiple copies of a single row in a list-style format. All rows must be part of the same database table. Titles for each field are shown above all the rows, with each row following on its own line. This form makes use of the form's optional parameter by adding the specified number of extra empty rows to the end of the list. If this field is left blank or 0, no extra rows are added.
Parameters:
OBJECT $iterator The row manager to use as a template for all rows.
ARRAY $fields Array of field objects (database fields) to include in the form.
OBJECT $form Form object these fieldsets will belong to.
INTEGER $numExtraRows The number of blank rows to display.
Returns:
ARRAY List of HorizontalFieldsets.
References $field, $fieldset, $i, $keyField, Fieldset::$showLabels, Form::getFormType(), RowManager::getPrimaryKeyName(), RowManager::getRowManagers(), and RowManager::getTableName().
The documentation for this class was generated from the following file:
OpenSiteAdmin/scripts/classes/Fieldsets/Fieldset_Horizontal.php