'TOME': admin/scripts/dbConverter.php File Reference
dbConverter.php File Reference
Functions
getSemester ($semester)
findDate ($semester)
makeFloat ($semester)
Variables
$path = "../../"
$data = file_get_contents("tomedb-hourly.sql", "r")
$lines = preg_split("/\r?\n/", $data[10])
foreach($lines as $line) $count = 0
$out = 'INSERT INTO `classes` (`class`, `name`, `comments`) VALUES'."\n"
$lines1 = $lines
$bookCount [] = 0
$booksLibrary = array()
$tomekeeperIDMap = array()
$tomekeeperLibraryMap = array()
$result = DatabaseManager::checkError("SELECT max(`ID`) +1 FROM `users`")
$tmp = DatabaseManager::fetchArray($result)
$start = $tmp[0]
$sql = "UPDATE `checkouts` join `books` on `books`.`ID` = `checkouts`.`bookID` SET `checkouts`.`bookTypeID` = `books`.`bookID`"
Function Documentation
findDate ($ semester)
Date February 13th
getSemester ($ semester)
References $tmp, and $year.
makeFloat ($ semester)
Variable Documentation
$bookCount[] = 0
$booksLibrary = array()
$count = 0
Referenced by countUniqueBooks().
$data = file_get_contents("tomedb-hourly.sql", "r")
Referenced by countUniqueBooks(), generateAccessTable(), ListManager::generateFilterForms(), ListManager::generateList(), and SingleFilter::getForm().
$lines = preg_split("/\r?\n/", $data[10])
$lines1 = $lines
foreach ($lines as $line) $out = 'INSERT INTO `classes` (`class`, `name`, `comments`) VALUES'."\n"
$path = "../../"
$result = DatabaseManager::checkError("SELECT max(`ID`) +1 FROM `users`")
$sql = "UPDATE `checkouts` join `books` on `books`.`ID` = `checkouts`.`bookID` SET `checkouts`.`bookTypeID` = `books`.`bookID`"
Referenced by getAvailableBooksForISBN(), getBookAvailability(), RowManager::getRowManagers(), RowManager::initialize(), LoginManager::login(), DeleteClassHook::process(), CheckoutFormHook::process(), CheckoutFormHook::sendNotificationEmail(), and LoginManager::suspend().
$start = $tmp[0]
$tmp = DatabaseManager::fetchArray($result)
Referenced by Fieldset::getDBValues(), getSemester(), getSemesterName(), Date::process(), and ProcessBookAssociationHook::process().
$tomekeeperIDMap = array()
$tomekeeperLibraryMap = array()