'TOME': OpenSiteAdmin/indexHeader.php File Reference
indexHeader.php File Reference
Functions
addPageLink (SecurityManager $securityManager, $path, $root, $type, $builtin)
addPage ($root, $builtin=false)
Variables
$path = "../"
$page = "index"
$securityManager = new SecurityManager($page)
Function Documentation
addPage ($ root, $ builtin = false)
Adds links to manage a database table to the admin index page.
Parameters:
STRING $root The root name to display ("user" or "access")
BOOLEAN $builtin True if this table is provided by the framework
Returns:
VOID
References $path, $securityManager, addPageLink(), and print.
addPageLink (SecurityManager $ securityManager, $ path, $ root, $ type, $ builtin)
Adds a single link to a page and checks visibility permissions.
Parameters:
OBJECT $securityManager SecurityManager object to use for visiblity checking.
STRING $path Path from this page to the site root.
STRING $type One of "add", "edit", or "delete"
BOOLEAN $builtin If true, looks for pages in OpenSiteAdmin/pages/ If false, looks for pages in admin/pages/.
Returns:
VOID
References $path, SecurityManager::isPageVisible(), and print.
Referenced by addPage().
Variable Documentation
$page = "index"
Referenced by SecurityManager::__construct(), SecurityManager::isPageVisible(), SecurityManager::isRowVisible(), and SecurityManager::validatePage().
$path = "../"
$securityManager = new SecurityManager($page)